language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
before_install:
    - apt-cache show libblas-dev
    - sudo apt-get update -qq -y
    - sudo apt-get install  chicken-bin liblapack-dev libblas-dev libsundials-serial-dev libsundials-cvode1 libsundials-ida2 libsundials-nvecserial0
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - sudo chicken-install mathh
    - sudo chicken-install
    - csi -s tests/run.scm
after_success:
        